/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V0_COMMONAPI_SPEED_SENSOR_SOMEIP_STUB_ADAPTER_HPP_
#define V0_COMMONAPI_SPEED_SENSOR_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/commonapi/SpeedSensorStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename _Stub = ::v0::commonapi::SpeedSensorStub, typename... _Stubs>
class SpeedSensorSomeIPStubAdapterInternal
    : public virtual SpeedSensorStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SpeedSensorSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SpeedSensorSomeIPStubAdapterHelper;

    ~SpeedSensorSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SpeedSensorSomeIPStubAdapterHelper::deinit();
    }

    void fireSpeedAttributeChanged(const uint32_t &_value);
    
    void fireRpmAttributeChanged(const uint32_t &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::SpeedSensorStub,
        CommonAPI::Version
    > getSpeedSensorInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::SpeedSensorStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getSpeedAttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v0::commonapi::SpeedSensorStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > setSpeedAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::SpeedSensorStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > getRpmAttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v0::commonapi::SpeedSensorStub,
        uint32_t,
        CommonAPI::SomeIP::IntegerDeployment<uint32_t>
    > setRpmAttributeStubDispatcher;
    
    SpeedSensorSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SpeedSensorSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SpeedSensorStub>(_stub)),
        getSpeedSensorInterfaceVersionStubDispatcher(&SpeedSensorStub::lockInterfaceVersionAttribute, &SpeedSensorStub::getInterfaceVersion, false, true),
        getSpeedAttributeStubDispatcher(
            &::v0::commonapi::SpeedSensorStub::lockSpeedAttribute,
            &::v0::commonapi::SpeedSensorStub::getSpeedAttribute,
            false,
            _stub->hasElement(0)),
        setSpeedAttributeStubDispatcher(
            &::v0::commonapi::SpeedSensorStub::lockSpeedAttribute,
            &::v0::commonapi::SpeedSensorStub::getSpeedAttribute,
            &SpeedSensorStubRemoteEvent::onRemoteSetSpeedAttribute,
            &SpeedSensorStubRemoteEvent::onRemoteSpeedAttributeChanged,
            &SpeedSensorStubAdapter::fireSpeedAttributeChanged,
            false,
            _stub->hasElement(0))
        ,
        getRpmAttributeStubDispatcher(
            &::v0::commonapi::SpeedSensorStub::lockRpmAttribute,
            &::v0::commonapi::SpeedSensorStub::getRpmAttribute,
            false,
            _stub->hasElement(1)),
        setRpmAttributeStubDispatcher(
            &::v0::commonapi::SpeedSensorStub::lockRpmAttribute,
            &::v0::commonapi::SpeedSensorStub::getRpmAttribute,
            &SpeedSensorStubRemoteEvent::onRemoteSetRpmAttribute,
            &SpeedSensorStubRemoteEvent::onRemoteRpmAttributeChanged,
            &SpeedSensorStubAdapter::fireRpmAttributeChanged,
            false,
            _stub->hasElement(1))
    {
        SpeedSensorSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3101) }, &getSpeedAttributeStubDispatcher );
        SpeedSensorSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3102) }, &setSpeedAttributeStubDispatcher );
        SpeedSensorSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3201) }, &getRpmAttributeStubDispatcher );
        SpeedSensorSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3202) }, &setRpmAttributeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>();

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x8150)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8150), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireSpeedAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::SpeedSensorStub>(_stub)->getSpeedAttribute(itsClient));
        }

        if (_stub->hasElement(1)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x81b4)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x81b4), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireRpmAttributeChanged(std::dynamic_pointer_cast< ::v0::commonapi::SpeedSensorStub>(_stub)->getRpmAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void SpeedSensorSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSpeedAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x8150),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void SpeedSensorSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireRpmAttributeChanged(const uint32_t &_value) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x81b4),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void SpeedSensorSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void SpeedSensorSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v0::commonapi::SpeedSensorStub, typename... _Stubs>
class SpeedSensorSomeIPStubAdapter
    : public SpeedSensorSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SpeedSensorSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SpeedSensorSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v0

#endif // V0_COMMONAPI_Speed_Sensor_SOMEIP_STUB_ADAPTER_HPP_
