/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_CAN_RECEIVER_Speed__Sensor_STUB_DEFAULT_HPP_
#define V1_CAN_RECEIVER_Speed__Sensor_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/Can_Receiver/Speed_SensorStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace Can_Receiver {

/**
 * Provides a default implementation for Speed_SensorStubRemoteEvent and
 * Speed_SensorStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT Speed_SensorStubDefault
    : public virtual Speed_SensorStub {
public:
    COMMONAPI_EXPORT Speed_SensorStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(Speed_Sensor::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT Speed_SensorStubRemoteEvent* initStubAdapter(const std::shared_ptr< Speed_SensorStubAdapter> &_adapter) {
        CommonAPI::Stub<Speed_SensorStubAdapter, Speed_SensorStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual const uint32_t &getSpeedAttribute() {
        return speedAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getSpeedAttribute();
    }
    COMMONAPI_EXPORT virtual void setSpeedAttribute(uint32_t _value) {
        const bool valueChanged = trySetSpeedAttribute(std::move(_value));
        if (valueChanged) {
            fireSpeedAttributeChanged(speedAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value) {
        (void)_client;
        setSpeedAttribute(_value);
    }
    COMMONAPI_EXPORT virtual const uint32_t &getRpmAttribute() {
        return rpmAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getRpmAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getRpmAttribute();
    }
    COMMONAPI_EXPORT virtual void setRpmAttribute(uint32_t _value) {
        const bool valueChanged = trySetRpmAttribute(std::move(_value));
        if (valueChanged) {
            fireRpmAttributeChanged(rpmAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setRpmAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value) {
        (void)_client;
        setRpmAttribute(_value);
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetSpeedAttribute(uint32_t _value) {
        if (!validateSpeedAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<Speed_SensorStubAdapter> stubAdapter = CommonAPI::Stub<Speed_SensorStubAdapter, Speed_SensorStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockSpeedAttribute(true);
            valueChanged = (speedAttributeValue_ != _value);
            speedAttributeValue_ = std::move(_value);
            stubAdapter->lockSpeedAttribute(false);
        } else {
            valueChanged = (speedAttributeValue_ != _value);
            speedAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateSpeedAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteSpeedAttributeChanged() {
        // No operation in default
    }
    COMMONAPI_EXPORT virtual bool trySetRpmAttribute(uint32_t _value) {
        if (!validateRpmAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<Speed_SensorStubAdapter> stubAdapter = CommonAPI::Stub<Speed_SensorStubAdapter, Speed_SensorStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockRpmAttribute(true);
            valueChanged = (rpmAttributeValue_ != _value);
            rpmAttributeValue_ = std::move(_value);
            stubAdapter->lockRpmAttribute(false);
        } else {
            valueChanged = (rpmAttributeValue_ != _value);
            rpmAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateRpmAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteRpmAttributeChanged() {
        // No operation in default
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual Speed_SensorStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(Speed_SensorStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }

        COMMONAPI_EXPORT virtual void onRemoteSpeedAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteSpeedAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetSpeedAttribute(uint32_t _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetSpeedAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value) {
            (void)_client;
            return onRemoteSetSpeedAttribute(_value);
        }
        COMMONAPI_EXPORT virtual void onRemoteRpmAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteRpmAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetRpmAttribute(uint32_t _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetRpmAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetRpmAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value) {
            (void)_client;
            return onRemoteSetRpmAttribute(_value);
        }

    private:
        Speed_SensorStubDefault *defaultStub_;
    };
protected:
    Speed_SensorStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    uint32_t speedAttributeValue_ {};
    uint32_t rpmAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace Can_Receiver
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_CAN_RECEIVER_Speed__Sensor_STUB_DEFAULT
