/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/Can_Receiver/Speed_SensorSomeIPStubAdapter.hpp>
#include <v1/Can_Receiver/Speed_Sensor.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace Can_Receiver {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createSpeed_SensorSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< Speed_SensorSomeIPStubAdapter<::v1::Can_Receiver::Speed_SensorStub>>(_address, _connection, _stub);
}

void initializeSpeed_SensorSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:Can_Receiver.Speed_Sensor:v1_0:Speed_Sensor",
         0x3000, 0x55f0, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "Can_Receiver.Speed_Sensor:v1_0",
        &createSpeed_SensorSomeIPStubAdapter);
}

INITIALIZER(registerSpeed_SensorSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSpeed_SensorSomeIPStubAdapter);
}

} // namespace Can_Receiver
} // namespace v1
