/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_MODERATOR_Service_Manager_PROXY_BASE_HPP_
#define V1_MODERATOR_Service_Manager_PROXY_BASE_HPP_

#include <v1/Moderator/ServiceManager.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Proxy.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace Moderator {

class ServiceManagerProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ObservableAttribute<uint32_t> SpeedAttribute;
    typedef CommonAPI::ObservableAttribute<uint32_t> RpmAttribute;
    typedef CommonAPI::ObservableAttribute<std::string> IndicatorAttribute;
    typedef CommonAPI::ObservableAttribute<std::string> GearAttribute;
    typedef CommonAPI::ObservableAttribute<uint8_t> BatteryAttribute;
    typedef CommonAPI::ObservableAttribute<float> VoltageAttribute;
    typedef CommonAPI::ObservableAttribute<float> CurrentAttribute;
    typedef CommonAPI::ObservableAttribute<uint8_t> PowerConsumptionAttribute;
    typedef CommonAPI::ObservableAttribute<std::string> GearSelectionAttribute;


    virtual SpeedAttribute& getSpeedAttribute() = 0;
    virtual RpmAttribute& getRpmAttribute() = 0;
    virtual IndicatorAttribute& getIndicatorAttribute() = 0;
    virtual GearAttribute& getGearAttribute() = 0;
    virtual BatteryAttribute& getBatteryAttribute() = 0;
    virtual VoltageAttribute& getVoltageAttribute() = 0;
    virtual CurrentAttribute& getCurrentAttribute() = 0;
    virtual PowerConsumptionAttribute& getPowerConsumptionAttribute() = 0;
    virtual GearSelectionAttribute& getGearSelectionAttribute() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace Moderator
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_MODERATOR_Service_Manager_PROXY_BASE_HPP_
