/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_MODERATOR_SERVICE_MANAGER_SOMEIP_PROXY_HPP_
#define V1_MODERATOR_SERVICE_MANAGER_SOMEIP_PROXY_HPP_

#include <v1/Moderator/ServiceManagerProxyBase.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Attribute.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace Moderator {

class ServiceManagerSomeIPProxy
    : virtual public ServiceManagerProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    ServiceManagerSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~ServiceManagerSomeIPProxy();

    virtual SpeedAttribute& getSpeedAttribute();

    virtual RpmAttribute& getRpmAttribute();

    virtual IndicatorAttribute& getIndicatorAttribute();

    virtual GearAttribute& getGearAttribute();

    virtual BatteryAttribute& getBatteryAttribute();

    virtual VoltageAttribute& getVoltageAttribute();

    virtual CurrentAttribute& getCurrentAttribute();

    virtual PowerConsumptionAttribute& getPowerConsumptionAttribute();

    virtual GearSelectionAttribute& getGearSelectionAttribute();

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<SpeedAttribute, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>> speed_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<RpmAttribute, CommonAPI::SomeIP::IntegerDeployment<uint32_t>>> rpm_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<IndicatorAttribute, CommonAPI::SomeIP::StringDeployment>> indicator_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<GearAttribute, CommonAPI::SomeIP::StringDeployment>> gear_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<BatteryAttribute, CommonAPI::SomeIP::IntegerDeployment<uint8_t>>> battery_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<VoltageAttribute>> voltage_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<CurrentAttribute>> current_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<PowerConsumptionAttribute, CommonAPI::SomeIP::IntegerDeployment<uint8_t>>> powerConsumption_;
    CommonAPI::SomeIP::ObservableAttribute<CommonAPI::SomeIP::Attribute<GearSelectionAttribute, CommonAPI::SomeIP::StringDeployment>> gearSelection_;

    std::promise<void> completed_;
};

} // namespace Moderator
} // namespace v1

#endif // V1_MODERATOR_Service_Manager_SOMEIP_PROXY_HPP_
