/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_Car__Control_STUB_HPP_
#define V0_COMMONAPI_Car__Control_STUB_HPP_

#include <functional>
#include <sstream>




#include <v0/commonapi/Car_Control.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#include <mutex>

#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service Car_Control. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class Car_ControlStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual Car_Control {
 public:
    ///Notifies all remote listeners about a change of value of the attribute indicator.
    virtual void fireIndicatorAttributeChanged(const std::string &indicator) = 0;
    ///Notifies all remote listeners about a change of value of the attribute gear.
    virtual void fireGearAttributeChanged(const uint8_t &gear) = 0;


    virtual void deactivateManagedInstances() = 0;

    void lockIndicatorAttribute(bool _lockAccess) {
        if (_lockAccess) {
            indicatorMutex_.lock();
        } else {
            indicatorMutex_.unlock();
        }
    }
    void lockGearAttribute(bool _lockAccess) {
        if (_lockAccess) {
            gearMutex_.lock();
        } else {
            gearMutex_.unlock();
        }
    }

protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */
    std::recursive_mutex indicatorMutex_;
    std::recursive_mutex gearMutex_;

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for Car_Control.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class Car_ControlStubRemoteEvent
{
public:
    virtual ~Car_ControlStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service Car_Control to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class Car_ControlStub
    : public virtual CommonAPI::Stub<Car_ControlStubAdapter, Car_ControlStubRemoteEvent>
{
public:

    virtual ~Car_ControlStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 2);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Provides getter access to the attribute indicator
    virtual const std::string &getIndicatorAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireIndicatorAttributeChanged(std::string _value) {
    auto stubAdapter = CommonAPI::Stub<Car_ControlStubAdapter, Car_ControlStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireIndicatorAttributeChanged(_value);
    }
    void lockIndicatorAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<Car_ControlStubAdapter, Car_ControlStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockIndicatorAttribute(_lockAccess);
    }
    /// Provides getter access to the attribute gear
    virtual const uint8_t &getGearAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) = 0;
    /// sets attribute with the given value and propagates it to the adapter
    virtual void fireGearAttributeChanged(uint8_t _value) {
    auto stubAdapter = CommonAPI::Stub<Car_ControlStubAdapter, Car_ControlStubRemoteEvent>::stubAdapter_.lock();
    if (stubAdapter)
        stubAdapter->fireGearAttributeChanged(_value);
    }
    void lockGearAttribute(bool _lockAccess) {
        auto stubAdapter = CommonAPI::Stub<Car_ControlStubAdapter, Car_ControlStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->lockGearAttribute(_lockAccess);
    }


    using CommonAPI::Stub<Car_ControlStubAdapter, Car_ControlStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<Car_ControlStubAdapter, Car_ControlStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<Car_ControlStubAdapter, Car_ControlStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef Car_ControlStubRemoteEvent RemoteEventType;
    typedef Car_Control StubInterface;
};

} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_Car__Control_STUB_HPP_
