/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_DES_PROJECT3_CAR__CONTROL_SOMEIP_STUB_ADAPTER_HPP_
#define V1_DES_PROJECT3_CAR__CONTROL_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/DES_Project3/Car_ControlStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace DES_Project3 {

template <typename _Stub = ::v1::DES_Project3::Car_ControlStub, typename... _Stubs>
class Car_ControlSomeIPStubAdapterInternal
    : public virtual Car_ControlStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< Car_ControlSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> Car_ControlSomeIPStubAdapterHelper;

    ~Car_ControlSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        Car_ControlSomeIPStubAdapterHelper::deinit();
    }

    void fireIndicatorAttributeChanged(const std::string &_value);
    
    void fireGearAttributeChanged(const std::string &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::DES_Project3::Car_ControlStub,
        CommonAPI::Version
    > getCar_ControlInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::DES_Project3::Car_ControlStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getIndicatorAttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::DES_Project3::Car_ControlStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > setIndicatorAttributeStubDispatcher;
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::DES_Project3::Car_ControlStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > getGearAttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::DES_Project3::Car_ControlStub,
        std::string,
        CommonAPI::SomeIP::StringDeployment
    > setGearAttributeStubDispatcher;
    
    Car_ControlSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        Car_ControlSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< Car_ControlStub>(_stub)),
        getCar_ControlInterfaceVersionStubDispatcher(&Car_ControlStub::lockInterfaceVersionAttribute, &Car_ControlStub::getInterfaceVersion, false, true),
        getIndicatorAttributeStubDispatcher(
            &::v1::DES_Project3::Car_ControlStub::lockIndicatorAttribute,
            &::v1::DES_Project3::Car_ControlStub::getIndicatorAttribute,
            false,
            _stub->hasElement(0)),
        setIndicatorAttributeStubDispatcher(
            &::v1::DES_Project3::Car_ControlStub::lockIndicatorAttribute,
            &::v1::DES_Project3::Car_ControlStub::getIndicatorAttribute,
            &Car_ControlStubRemoteEvent::onRemoteSetIndicatorAttribute,
            &Car_ControlStubRemoteEvent::onRemoteIndicatorAttributeChanged,
            &Car_ControlStubAdapter::fireIndicatorAttributeChanged,
            false,
            _stub->hasElement(0))
        ,
        getGearAttributeStubDispatcher(
            &::v1::DES_Project3::Car_ControlStub::lockGearAttribute,
            &::v1::DES_Project3::Car_ControlStub::getGearAttribute,
            false,
            _stub->hasElement(1)),
        setGearAttributeStubDispatcher(
            &::v1::DES_Project3::Car_ControlStub::lockGearAttribute,
            &::v1::DES_Project3::Car_ControlStub::getGearAttribute,
            &Car_ControlStubRemoteEvent::onRemoteSetGearAttribute,
            &Car_ControlStubRemoteEvent::onRemoteGearAttributeChanged,
            &Car_ControlStubAdapter::fireGearAttributeChanged,
            false,
            _stub->hasElement(1))
    {
        Car_ControlSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4101) }, &getIndicatorAttributeStubDispatcher );
        Car_ControlSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4102) }, &setIndicatorAttributeStubDispatcher );
        Car_ControlSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4201) }, &getGearAttributeStubDispatcher );
        Car_ControlSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x4202) }, &setGearAttributeStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>(0xFFFF, 0xFFFFFFFF, 0xFFFFFFFF);

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0xac48)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xac48), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireIndicatorAttributeChanged(std::dynamic_pointer_cast< ::v1::DES_Project3::Car_ControlStub>(_stub)->getIndicatorAttribute(itsClient));
        }

        if (_stub->hasElement(1)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0xacac)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0xacac), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
            fireGearAttributeChanged(std::dynamic_pointer_cast< ::v1::DES_Project3::Car_ControlStub>(_stub)->getGearAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void Car_ControlSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireIndicatorAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xac48),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void Car_ControlSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireGearAttributeChanged(const std::string &_value) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployedValue(_value, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0xacac),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void Car_ControlSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void Car_ControlSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::DES_Project3::Car_ControlStub, typename... _Stubs>
class Car_ControlSomeIPStubAdapter
    : public Car_ControlSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    Car_ControlSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          Car_ControlSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace DES_Project3
} // namespace v1

#endif // V1_DES_PROJECT3_Car__Control_SOMEIP_STUB_ADAPTER_HPP_
