/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_DES_PROJECT3_Car__Information_PROXY_HPP_
#define V1_DES_PROJECT3_Car__Information_PROXY_HPP_

#include <v1/DES_Project3/Car_InformationProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace DES_Project3 {

template <typename ... _AttributeExtensions>
class Car_InformationProxy
    : virtual public Car_Information,
      virtual public Car_InformationProxyBase,
      virtual public _AttributeExtensions... {
public:
    Car_InformationProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~Car_InformationProxy();

    typedef Car_Information InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute battery.
     */
    virtual BatteryAttribute& getBatteryAttribute() {
        return delegate_->getBatteryAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute voltage.
     */
    virtual VoltageAttribute& getVoltageAttribute() {
        return delegate_->getVoltageAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute current.
     */
    virtual CurrentAttribute& getCurrentAttribute() {
        return delegate_->getCurrentAttribute();
    }
    /**
     * Returns the wrapper class that provides access to the attribute powerConsumption.
     */
    virtual PowerConsumptionAttribute& getPowerConsumptionAttribute() {
        return delegate_->getPowerConsumptionAttribute();
    }



 private:
    std::shared_ptr< Car_InformationProxyBase> delegate_;
};

typedef Car_InformationProxy<> Car_InformationProxyDefault;

namespace Car_InformationExtensions {
    template <template <typename > class _ExtensionType>
    class BatteryAttributeExtension {
     public:
        typedef _ExtensionType< Car_InformationProxyBase::BatteryAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< Car_InformationProxyBase::BatteryAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        BatteryAttributeExtension(Car_InformationProxyBase& proxy): attributeExtension_(proxy.getBatteryAttribute()) {
        }
    
        inline extension_type& getBatteryAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class VoltageAttributeExtension {
     public:
        typedef _ExtensionType< Car_InformationProxyBase::VoltageAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< Car_InformationProxyBase::VoltageAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        VoltageAttributeExtension(Car_InformationProxyBase& proxy): attributeExtension_(proxy.getVoltageAttribute()) {
        }
    
        inline extension_type& getVoltageAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class CurrentAttributeExtension {
     public:
        typedef _ExtensionType< Car_InformationProxyBase::CurrentAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< Car_InformationProxyBase::CurrentAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        CurrentAttributeExtension(Car_InformationProxyBase& proxy): attributeExtension_(proxy.getCurrentAttribute()) {
        }
    
        inline extension_type& getCurrentAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

    template <template <typename > class _ExtensionType>
    class PowerConsumptionAttributeExtension {
     public:
        typedef _ExtensionType< Car_InformationProxyBase::PowerConsumptionAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< Car_InformationProxyBase::PowerConsumptionAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        PowerConsumptionAttributeExtension(Car_InformationProxyBase& proxy): attributeExtension_(proxy.getPowerConsumptionAttribute()) {
        }
    
        inline extension_type& getPowerConsumptionAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace Car_InformationExtensions

//
// Car_InformationProxy Implementation
//
template <typename ... _AttributeExtensions>
Car_InformationProxy<_AttributeExtensions...>::Car_InformationProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< Car_InformationProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< Car_InformationProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
Car_InformationProxy<_AttributeExtensions...>::~Car_InformationProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &Car_InformationProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool Car_InformationProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool Car_InformationProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& Car_InformationProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& Car_InformationProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> Car_InformationProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace DES_Project3
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::DES_Project3::Car_InformationProxy,
    _AttributeExtension> {
    typedef typename ::v1::DES_Project3::Car_InformationProxy<
            ::v1::DES_Project3::Car_InformationExtensions::BatteryAttributeExtension<_AttributeExtension>, 
            ::v1::DES_Project3::Car_InformationExtensions::VoltageAttributeExtension<_AttributeExtension>, 
            ::v1::DES_Project3::Car_InformationExtensions::CurrentAttributeExtension<_AttributeExtension>, 
            ::v1::DES_Project3::Car_InformationExtensions::PowerConsumptionAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_DES_PROJECT3_Car__Information_PROXY_HPP_
