/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/DES_Project3/Car_ControlSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace DES_Project3 {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createCar_ControlSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< Car_ControlSomeIPProxy>(_address, _connection);
}

void initializeCar_ControlSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:DES_Project3.Car_Control:v1_0:Car_Control",
        0x4000, 0x55fa, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "DES_Project3.Car_Control:v1_0",
        &createCar_ControlSomeIPProxy);
}

INITIALIZER(registerCar_ControlSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeCar_ControlSomeIPProxy);
}

Car_ControlSomeIPProxy::Car_ControlSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          indicator_(*this, CommonAPI::SomeIP::eventgroup_id_t(0xac48), CommonAPI::SomeIP::event_id_t(0xac48), CommonAPI::SomeIP::method_id_t(0x4101), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, CommonAPI::SomeIP::method_id_t(0x4102), true, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
          gear_(*this, CommonAPI::SomeIP::eventgroup_id_t(0xacac), CommonAPI::SomeIP::event_id_t(0xacac), CommonAPI::SomeIP::method_id_t(0x4201), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, CommonAPI::SomeIP::method_id_t(0x4202), true, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr))
{
}

Car_ControlSomeIPProxy::~Car_ControlSomeIPProxy() {
    completed_.set_value();
}

Car_ControlSomeIPProxy::IndicatorAttribute& Car_ControlSomeIPProxy::getIndicatorAttribute() {
    return indicator_;
}
Car_ControlSomeIPProxy::GearAttribute& Car_ControlSomeIPProxy::getGearAttribute() {
    return gear_;
}


void Car_ControlSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> Car_ControlSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace DES_Project3
} // namespace v1
