/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/DES_Project3/HUSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace DES_Project3 {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createHUSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< HUSomeIPProxy>(_address, _connection);
}

void initializeHUSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:DES_Project3.HU:v1_0:HU",
        0x2000, 0x560e, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "DES_Project3.HU:v1_0",
        &createHUSomeIPProxy);
}

INITIALIZER(registerHUSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeHUSomeIPProxy);
}

HUSomeIPProxy::HUSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          gearSelection_(*this, CommonAPI::SomeIP::eventgroup_id_t(0xcbec), CommonAPI::SomeIP::event_id_t(0xcbec), CommonAPI::SomeIP::method_id_t(0x2201), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, CommonAPI::SomeIP::method_id_t(0x2202), true, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr))
{
}

HUSomeIPProxy::~HUSomeIPProxy() {
    completed_.set_value();
}

HUSomeIPProxy::GearSelectionAttribute& HUSomeIPProxy::getGearSelectionAttribute() {
    return gearSelection_;
}


void HUSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> HUSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace DES_Project3
} // namespace v1
