/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_DES_PROJECT3_IC_STUB_DEFAULT_HPP_
#define V1_DES_PROJECT3_IC_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/DES_Project3/ICStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace DES_Project3 {

/**
 * Provides a default implementation for ICStubRemoteEvent and
 * ICStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT ICStubDefault
    : public virtual ICStub {
public:
    COMMONAPI_EXPORT ICStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(IC::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT ICStubRemoteEvent* initStubAdapter(const std::shared_ptr< ICStubAdapter> &_adapter) {
        CommonAPI::Stub<ICStubAdapter, ICStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void setRpm(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _filteredRpm, setRpmReply_t _reply) {
        (void)_client;
        (void)_filteredRpm;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setSpeed(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _filteredSpeed, setSpeedReply_t _reply) {
        (void)_client;
        (void)_filteredSpeed;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setGear(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _currentGear, setGearReply_t _reply) {
        (void)_client;
        (void)_currentGear;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setCurrent(const std::shared_ptr<CommonAPI::ClientId> _client, float _current, setCurrentReply_t _reply) {
        (void)_client;
        (void)_current;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setPowerConsumption(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _powerconsumption, setPowerConsumptionReply_t _reply) {
        (void)_client;
        (void)_powerconsumption;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setVoltage(const std::shared_ptr<CommonAPI::ClientId> _client, float _voltage, setVoltageReply_t _reply) {
        (void)_client;
        (void)_voltage;
        std::string message = "";
        _reply(message);
    }
    COMMONAPI_EXPORT virtual void setBatteryLevel(const std::shared_ptr<CommonAPI::ClientId> _client, uint8_t _batterylevel, setBatteryLevelReply_t _reply) {
        (void)_client;
        (void)_batterylevel;
        std::string message = "";
        _reply(message);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual ICStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(ICStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        ICStubDefault *defaultStub_;
    };
protected:
    ICStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace DES_Project3
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_DES_PROJECT3_IC_STUB_DEFAULT
