/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_Car_Info_PROXY_HPP_
#define V0_COMMONAPI_Car_Info_PROXY_HPP_

#include <v0/commonapi/CarInfoProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {

template <typename ... _AttributeExtensions>
class CarInfoProxy
    : virtual public CarInfo,
      virtual public CarInfoProxyBase,
      virtual public _AttributeExtensions... {
public:
    CarInfoProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~CarInfoProxy();

    typedef CarInfo InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Returns the wrapper class that provides access to the attribute battery.
     */
    virtual BatteryAttribute& getBatteryAttribute() {
        return delegate_->getBatteryAttribute();
    }



 private:
    std::shared_ptr< CarInfoProxyBase> delegate_;
};

typedef CarInfoProxy<> CarInfoProxyDefault;

namespace CarInfoExtensions {
    template <template <typename > class _ExtensionType>
    class BatteryAttributeExtension {
     public:
        typedef _ExtensionType< CarInfoProxyBase::BatteryAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< CarInfoProxyBase::BatteryAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        BatteryAttributeExtension(CarInfoProxyBase& proxy): attributeExtension_(proxy.getBatteryAttribute()) {
        }
    
        inline extension_type& getBatteryAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace CarInfoExtensions

//
// CarInfoProxy Implementation
//
template <typename ... _AttributeExtensions>
CarInfoProxy<_AttributeExtensions...>::CarInfoProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< CarInfoProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< CarInfoProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
CarInfoProxy<_AttributeExtensions...>::~CarInfoProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &CarInfoProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool CarInfoProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool CarInfoProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& CarInfoProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& CarInfoProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> CarInfoProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace commonapi
} // namespace v0

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v0::commonapi::CarInfoProxy,
    _AttributeExtension> {
    typedef typename ::v0::commonapi::CarInfoProxy<
            ::v0::commonapi::CarInfoExtensions::BatteryAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_Car_Info_PROXY_HPP_
